BEGIN TRANSACTION;
insert into compagny values(1, 'Bruker');
insert into compagny values(2, 'Oxford Instrument');
insert into compagny values(3, 'Homemade');
insert into brand values(1, 'Bruker',1);
insert into brand values(2, 'JPK',1);
insert into brand values(3, 'Asylum Research',2);
insert into brand values(4, 'Homemade', 3);
insert into model values(1, 'multimode',1);
insert into model values(2, 'dimension 3000',1);
insert into model values(3, 'dimension 3100',1);
insert into model values(4, 'dimension Icon',1);
insert into model values(5, 'Edge',1);
insert into model values(6, 'dimension XR',1);
insert into model values(7, 'dimension FastScan',1);
insert into model values(8, 'dimension Icon Raman',1);
insert into model values(9, 'MultiMode 8 HR',1);
insert into model values(10, 'Innova',1);
insert into model values(11, 'Nanowizard',2);
insert into model values(12, 'NanoWizard NanoOptics',2);
insert into model values(13, 'NanoWizard 4 XP NanoScience',2);
insert into model values(15, 'MFP3D origin',3);
insert into model values(16, 'MFP3D Infinity',3);
insert into model values(17, 'MFP3D Bio',3);
insert into model values(18, 'Cypher S',3);
insert into model values(19, 'Cypher ES',3);
insert into model values(20, 'Cypher ES polymer',3);
insert into model values(21, 'Cypher VRS',3);
insert into model values(22, 'Jupiter XR',3);
insert into model values(23, 'Homemade',4);
insert into controller values(1, 'Nanoscope IIIa',1);
insert into controller values(2, 'Nanoscope Quadrex',1);
insert into controller values(3, 'Nanoscope V',1);
insert into controller values(4, 'Nanoscope 6',1);
insert into controller values(15, 'ARC2',3);
insert into category values(NULL, 'Environnement');
insert into category values(NULL, 'Modes');
insert into category values(NULL, 'Matériaux');
insert into category values(NULL, 'Thématiques');
insert into keyword values(1,1,'Milieu liquide');
insert into keyword values(2,1,'Ultravide');
insert into keyword values(3,1,'Vide');
insert into keyword values(4,1,'Air');
insert into keyword values(5,1,'Atmosphère contrôlée');
insert into keyword values(6,2,'Contact');
insert into keyword values(7,2,'Tapping');
insert into keyword values(8,2,'Non contact');
insert into keyword values(9,2,'Spectroscopie');
insert into keyword values(10,2,'Q+');
insert into keyword values(11,2,'SCM');
insert into keyword values(12,2,'SSRM');
insert into keyword values(13,2,'CAFM');
insert into keyword values(14,2,'SThM');
insert into keyword values(15,2,'KPFM');
insert into keyword values(16,2,'EFM');
insert into keyword values(17,2,'PFAFM');
insert into keyword values(18,2,'FluidFM');
insert into keyword values(19,2,'PFM');
insert into keyword values(20,2,'Nanoindentation');
insert into keyword values(21,2,'Nanolithographie');
insert into keyword values(22,2,'Nanomanipulation');
insert into keyword values(23,2,'LFM');
insert into keyword values(24,2,'MFM');
insert into keyword values(25,2,'STM');
insert into keyword values(26,3,'Oxydes');
insert into keyword values(27,3,'Métaux');
insert into keyword values(28,3,'Polymère');
insert into keyword values(29,3,'Minéraux');
insert into keyword values(30,3,'Molécule');
insert into keyword values(31,3,'Graphène');
insert into keyword values(32,3,'Bois');
insert into keyword values(33,3,'Semi-conducteur');
insert into keyword values(34,3,'Organique');
insert into keyword values(35,4,'Biologie');
insert into keyword values(36,4,'Matériaux mous');
insert into keyword values(37,4,'Rhéologie');
insert into keyword values(38,4,'Magnétisme');
insert into keyword values(39,4,'Couches minces');
insert into keyword values(40,4,'Autoorganisation');
insert into keyword values(41,4,'Basse température');
insert into keyword values(42,4,'AFM rapide');
insert into keyword values(43,4,'Batterie');
COMMIT;
